### ISSUE TITLE
pex.interpreter.InterpreterNotFound

### ISSUE THREAD

**Issue by ASH1998** [Chentai-Kao/codemap-public#10]
Installing pex does not work.
The python environment at the given address is working perfectly.
Python 3.7.9

```Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\lik\AppData\Local\Programs\codemap\resources\app.asar.unpacked\public\parsers\python_parser\parser.pex\__main__.py", line 68, in <module>
  File "C:\Users\lik\AppData\Local\Programs\codemap\resources\app.asar.unpacked\public\parsers\python_parser\parser.pex\.bootstrap\pex\pex_bootstrapper.py", line 243, in bootstrap_pex
  File "C:\Users\lik\AppData\Local\Programs\codemap\resources\app.asar.unpacked\public\parsers\python_parser\parser.pex\.bootstrap\pex\pex_bootstrapper.py", line 156, in maybe_reexec_pex
  File "C:\Users\lik\AppData\Local\Programs\codemap\resources\app.asar.unpacked\public\parsers\python_parser\parser.pex\.bootstrap\pex\interpreter.py", line 263, in get
  File "C:\Users\lik\AppData\Local\Programs\codemap\resources\app.asar.unpacked\public\parsers\python_parser\parser.pex\.bootstrap\pex\interpreter.py", line 436, in from_binary
  File "C:\Users\lik\AppData\Local\Programs\codemap\resources\app.asar.unpacked\public\parsers\python_parser\parser.pex\.bootstrap\pex\interpreter.py", line 417, in _spawn_from_binary
pex.interpreter.InterpreterNotFound: C:\Users\lik\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\python.exe```

**Comment by Chentai-Kao** [comment]
Hi @ASH1998 , are you saying the `C:\Users\lik\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\python.exe` file exists and that `python.exe` is working perfectly?

Does running `python3` in your terminal works? Codemap invokes `python3` to run the parser, so if `python3` is missing it may lead to some problem.

**Comment by Chentai-Kao** [comment]
Hi @ASH1998 I've released a new version of Codemap that supports customized Python path and shouldn't throw this error anymore. Could you try it out at https://codemap.app? Thanks.
